"""What is known not to work, so nobody has to rediscover it. Open items only: fixed things
leave this list (git history keeps them). status: open (a bug we could not crack yet),
unverified (code exists, never ran through), limit (the site offers nothing to build on),
by_design (a deliberate choice)."""

from __future__ import annotations

KNOWN_ISSUES: list[dict[str, str]] = [
    {
        "id": "weixin_mp_appmsg",
        "platform": "weixin_mp",
        "status": "unverified",
        "since": "2026-09-07",
        "title": "公众号文章列表（get_user_posts）没跑通",
        "title_en": "公众号 article list (get_user_posts) never ran through",
        "detail": "appmsg 接口第一次调用就返回 freq control，账号被冻结，代码写完但没有样本；解冻后录样本再验证。",
        "detail_en": "The appmsg endpoint answered \"freq control\" on the first call and froze the account; the code exists but has no recorded sample until the account thaws.",
    },
    {
        "id": "weixin_channels",
        "platform": "weixin_channels",
        "status": "by_design",
        "since": "2026-09-07",
        "title": "视频号只有骨架",
        "title_en": "视频号 is a skeleton only",
        "detail": "网页端没有公域入口（只有创作者后台和分享链接播放页），后台数据接口留到做社媒后台管理工具时再做。",
        "detail_en": "The web has no public surface (only the creator backstage and share-link players); the backstage APIs wait for a creator-tools project.",
    },
    {
        "id": "kuaishou_replies",
        "platform": "kuaishou",
        "status": "limit",
        "since": "2026-09-07",
        "title": "快手没有评论回复",
        "title_en": "快手 has no comment replies",
        "detail": "网页版评论接口不带子评论信息，get_replies 不支持。",
        "detail_en": "The web comment endpoint carries no child comments, so get_replies is unsupported.",
    },
    {
        "id": "linkedin_search",
        "platform": "linkedin",
        "status": "limit",
        "since": "2026-09-08",
        "title": "LinkedIn 没有内容搜索和热榜",
        "title_en": "LinkedIn has no post search or trending",
        "detail": "新版网页全是 RSC + SDUI 组件树，只有老 voyager 接口和老版 Ember 页面能拿到数据；内容搜索没有对应入口。",
        "detail_en": "The new web app is RSC + SDUI component trees; only the legacy voyager endpoints and Ember pages expose data, and post search has none.",
    },
    {
        "id": "toutiao_users",
        "platform": "toutiao",
        "status": "limit",
        "since": "2026-09-08",
        "title": "头条没有用户搜索",
        "title_en": "头条 has no user search",
        "detail": "so.toutiao.com 只有资讯 / 视频等标签，没有用户结果。",
        "detail_en": "so.toutiao.com only has news / video tabs, no people results.",
    },
    {
        "id": "xiaohongshu_search_risk",
        "platform": "xiaohongshu",
        "status": "open",
        "since": "2026-09-07",
        "title": "小红书搜索容易触发限流",
        "title_en": "小红书 search trips its rate limit easily",
        "detail": "实测同一关键词一小时内搜约六次后搜索接口报错，其他接口不受影响；整站空正文的软封锁按出口 IP 计。只能等，或换网络出口。风控命中现在会记到 /risk/events。",
        "detail_en": "About six searches of one keyword within an hour made the search endpoint fail (other endpoints unaffected); the site-wide empty-body soft block is per egress IP. Wait, or change the egress. Hits are now logged at /risk/events.",
    },
    {
        "id": "yt_dlp_downloads",
        "platform": "youtube",
        "status": "limit",
        "since": "2026-09-07",
        "title": "YouTube / TikTok 下载依赖 yt-dlp 和代理",
        "title_en": "YouTube / TikTok downloads need yt-dlp and a proxy",
        "detail": "网页流地址要 PO token，页面内请求也 403，所以走 yt-dlp（uv sync --extra download）；本机直连 youtube.com 会被断，下载沿用系统代理。get_streams 只是 progressive 模式的实验。",
        "detail_en": "Stream urls need a PO token and 403 even from inside the page, so downloads go through yt-dlp (uv sync --extra download) and follow the system proxy; get_streams is a progressive-mode experiment only.",
    },
    {
        "id": "reddit_audio",
        "platform": "reddit",
        "status": "limit",
        "since": "2026-09-07",
        "title": "Reddit 视频的音轨可能下不到",
        "title_en": "Reddit video audio may fail",
        "detail": "v.redd.it 是分离的 DASH 视频和音频，音轨有时 403，下载时可选跳过音轨。",
        "detail_en": "v.redd.it serves separate DASH video and audio; the audio track sometimes 403s and can be skipped.",
    },
    {
        "id": "tabs_update",
        "platform": "extension",
        "status": "open",
        "since": "2026-09-29",
        "title": "扩展无法就地导航自己的标签页",
        "title_en": "The extension cannot navigate its own tabs in place",
        "detail": "tabs.update({url}) 在任务路径里永远不提交（pendingUrl 挂着、旧文档活着，有头无头 Chromium 都一样，在 SW 控制台直接调却正常），根因没查清。现在顶替标签页是关旧页在同位置新建，效果相同，只是页面会闪一下。",
        "detail_en": "tabs.update({url}) never commits from the task path (pending url, old document alive, headed and headless alike, while the same call from the SW console works); root cause unknown. Tabs are now replaced by closing and recreating at the same index, which looks like a flicker.",
    },
    {
        "id": "matcher_flags",
        "platform": "extension",
        "status": "by_design",
        "since": "2026-09-29",
        "title": "捕获模式的尾段像正则 flag 时会被当正则",
        "title_en": "A capture pattern whose last segment looks like regex flags is parsed as a regex",
        "detail": "像 /api/x/y 这样最后一段全是 g i m s u y 字母的路径会被解析成带 flag 的正则（y 是 sticky），匹配失败。模式以斜杠结尾即可避开。",
        "detail_en": "A path like /api/x/y whose last segment is only g i m s u y letters parses as a flagged regex (y is sticky) and fails to match. End patterns with a slash.",
    },
    {
        "id": "chrome_stuck",
        "platform": "extension",
        "status": "limit",
        "since": "2026-09-07",
        "title": "Chrome 会进入不再加载新标签页的状态",
        "title_en": "Chrome can enter a state where new tabs never load",
        "detail": "工作窗口里堆太多标签页后，Chrome 新建的标签页 URL 为空、永不加载，所有页面任务超时而扩展后台正常。现在概览页会识别这种情况并提示完全退出重开；扩展自己的标签页有数量上限和闲置回收，并会顶替复用。",
        "detail_en": "After too many tabs pile up in the work window, new tabs open with an empty url and never load: every page task times out while the extension's background is fine. The overview now detects this and says to quit and reopen Chrome; owned tabs are capped, recycled when idle, and reused.",
    },
    {
        "id": "chrome_stable_automation",
        "platform": "general",
        "status": "limit",
        "since": "2026-09-06",
        "title": "正式版 Chrome 不能用于自动化测试",
        "title_en": "Stable Chrome cannot be used for automated tests",
        "detail": "Chrome 137 起忽略 --load-extension，端到端脚本必须用 Playwright 的 Chromium；裸 CDP 直连扩展 worker 拿不到 chrome.* API。只影响测试，不影响使用。",
        "detail_en": "Chrome 137+ ignores --load-extension, so the e2e script must use Playwright's Chromium; raw CDP into the worker has no chrome.* APIs. Tests only, not daily use.",
    },
]
